version: '3.8'

services:
  text-classifier-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-classifier-api
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
    volumes:
      # Optional: mount model weight directory locally to receive newly trained updates
      - ./app/model:/workspace/app/model
    restart: unless-stopped
